In [43]:
import torch
from torchsummary import summary
import warnings

warnings.filterwarnings('ignore')

In [46]:
from src.models import XOR
from src.dataloader import XOR_weights_init
from src.train import *

In [133]:
model = XOR()
print(model)

XOR(
  (lin1): Linear(in_features=2, out_features=5, bias=True)
  (lin2): Linear(in_features=5, out_features=4, bias=True)
  (lin3): Linear(in_features=4, out_features=1, bias=True)
)


In [134]:
summary(model, (2,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 5]              15
            Linear-2                    [-1, 4]              24
            Linear-3                    [-1, 1]               5
Total params: 44
Trainable params: 44
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [135]:
X = torch.Tensor([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = torch.Tensor([0, 1, 1, 0]).view(-1, 1)

In [136]:
XOR_weights_init(model)

In [137]:
for i in model.parameters():
    print(i)

Parameter containing:
tensor([[ 0.4695,  0.5565],
        [ 1.2026, -0.0230],
        [-0.4813, -1.0190],
        [ 2.3466, -0.4679],
        [ 2.1102, -0.9591]], requires_grad=True)
Parameter containing:
tensor([ 0.2665, -0.2179, -0.0635,  0.1505,  0.3399], requires_grad=True)
Parameter containing:
tensor([[-0.7559,  0.2280,  1.4137, -1.1880, -0.8524],
        [ 0.2864, -0.2139, -0.7492, -0.5393,  0.4296],
        [-0.8712, -0.6346,  0.5067,  1.0927,  1.2096],
        [ 1.8963, -0.5460, -0.2441, -1.4945, -0.1910]], requires_grad=True)
Parameter containing:
tensor([ 0.3599, -0.3621, -0.0880,  0.1859], requires_grad=True)
Parameter containing:
tensor([[-0.1567,  0.6433, -1.3445, -0.1789]], requires_grad=True)
Parameter containing:
tensor([-0.0328], requires_grad=True)


In [139]:
train_XOR(model,X,Y, epoch=2001, lr=0.02, momentum=0.9)

Epoch: 0, Loss: 0.4999694526195526, 
Epoch: 50, Loss: 0.010788977146148682, 
Epoch: 100, Loss: 0.29012930393218994, 
Epoch: 150, Loss: 0.05014169216156006, 
Epoch: 200, Loss: 0.005144000053405762, 
Epoch: 250, Loss: 0.09362256526947021, 
Epoch: 300, Loss: 0.07384943962097168, 
Epoch: 350, Loss: 0.24671411514282227, 
Epoch: 400, Loss: 0.07530450820922852, 
Epoch: 450, Loss: 0.11173248291015625, 
Epoch: 500, Loss: 0.19386684894561768, 
Epoch: 550, Loss: 0.04457557201385498, 
Epoch: 600, Loss: 0.08513343334197998, 
Epoch: 650, Loss: 0.06022578477859497, 
Epoch: 700, Loss: 0.5702915191650391, 
Epoch: 750, Loss: 0.016708433628082275, 
Epoch: 800, Loss: 0.02219313383102417, 
Epoch: 850, Loss: 0.0005142688751220703, 
Epoch: 900, Loss: 0.15464657545089722, 
Epoch: 950, Loss: 0.0053064823150634766, 
Epoch: 1000, Loss: 0.7382036447525024, 
Epoch: 1050, Loss: 0.11855697631835938, 
Epoch: 1100, Loss: 0.3361349105834961, 
Epoch: 1150, Loss: 0.36813414096832275, 
Epoch: 1200, Loss: 0.062236547470092